"""Shared random-start HyCoRe warmup, then paired B1/B2 HIER training.

The warmup checkpoint is generated by this script. It never loads the old
epoch-229 checkpoint or an old teacher feature cache. Part clouds use the two
in-place, sequential ``get_children_np`` calls from original HyCoRe.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import json
import math
import os
from pathlib import Path
import random
import subprocess
import sys
import time

os.environ.setdefault("HDF5_USE_FILE_LOCKING", "FALSE")
HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "pointnet2_ops_lib"))
sys.path.insert(0, str(HERE.parent))

import geoopt
import numpy as np
import torch
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader

from hutil import cal_loss, get_children_np, hype_triplet_losses
from models.pointmlp import Hype_pointMLP
from v2.sampler import ClassBalancedBatchSampler
from hier_proxy_v2_online.mining import mine_batch_triplets
from hier_proxy_v2_online.proxy_hierarchy import ProxyHierarchy
from hier_proxy_v2_online.diagnostics import fixed_rng, fixed_triplet_metrics, proxy_geometry
from hier_proxy_v2_online.train import (
    PointClouds, assert_manifold_contract, calibrate, edge_jaccard, evaluate,
    fixed_probe_data, git_branch, git_commit, initialization_features,
    load_shards, norm_of_gradient,
    probe_distance_stats, probe_neighbour_edges, seed_all, sha256, triplet_columns,
)


ALPHA_INTRA = 0.01
MAX_BETA = 10.0
BACKBONE_PREFIXES = (
    "embedding", "local_grouper_list", "pre_blocks_list", "pos_blocks_list",
    "proj", "emb", "classifier",
)


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--phase", required=True, choices=("warmup", "branch"))
    parser.add_argument("--arm", choices=("B1", "B2"))
    parser.add_argument("--warmup-checkpoint", type=Path)
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--seed", type=int, default=22)
    parser.add_argument("--epochs", type=int, default=300)
    parser.add_argument("--warmup-epochs", type=int, default=20)
    parser.add_argument("--ramp-epochs", type=int, default=20)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--save-every", type=int, default=10)
    parser.add_argument("--max-batches", type=int, default=0, help="smoke only; zero means 307")
    parser.add_argument("--skip-test", action="store_true", help="smoke only")
    parser.add_argument("--calibration-batches", type=int, default=4)
    parser.add_argument("--proxy-lr-ceiling", type=float, default=5e-4)
    parser.add_argument("--target-hier-scale", type=float, default=3.0)
    parser.add_argument("--k-in", type=int, default=3)
    parser.add_argument("--proxy-count", type=int, default=128)
    parser.add_argument("--proxy-k", type=int, default=8)
    parser.add_argument("--proxy-triples-per-anchor", type=int, default=2)
    parser.add_argument("--tau", type=float, default=0.1)
    parser.add_argument("--margin", type=float, default=0.1)
    args = parser.parse_args()
    if args.phase == "branch" and (args.arm is None or args.warmup_checkpoint is None):
        parser.error("branch requires --arm and --warmup-checkpoint")
    if args.phase == "warmup" and (args.arm is not None or args.warmup_checkpoint is not None):
        parser.error("warmup cannot use --arm or --warmup-checkpoint")
    if not 0 < args.warmup_epochs < args.epochs or args.ramp_epochs < 1:
        parser.error("require 0 < warmup-epochs < epochs and positive ramp-epochs")
    if args.workers < 0 or args.max_batches < 0 or args.save_every < 1:
        parser.error("invalid worker, batch, or save interval")
    if args.calibration_batches < 1 or args.proxy_lr_ceiling <= 0:
        parser.error("calibration batches and proxy LR ceiling must be positive")
    if args.k_in < 1 or args.k_in > 6 or not 2 <= args.proxy_k < args.proxy_count:
        parser.error("invalid HIER neighborhood sizes for 4x8 batch")
    if not math.isfinite(args.target_hier_scale) or args.target_hier_scale <= 0:
        parser.error("target hierarchy scale must be positive")
    args.classes_per_batch = 4
    args.samples_per_class = 8
    args.batch_size = 32
    args.num_points = 1024
    args.steps_per_epoch = 307
    args.lr = 0.1
    args.min_lr = 0.005
    args.weight_decay = 2e-4
    args.teacher_views = 1
    return args


def serializable_args(args: argparse.Namespace) -> dict:
    return {key: str(value) if isinstance(value, Path) else value
            for key, value in vars(args).items()}


@torch.no_grad()
def initialize_proxies_from_features(
        proxy: ProxyHierarchy, reference_mu: torch.Tensor) -> dict:
    """Use epoch-20 whole features for proxy directions, without class labels.

    The original v2 initializer used the feature median only as a scale and
    placed proxies in random directions. Here a fixed subset is clustered in
    the origin tangent space, then the cluster directions are placed at the
    same conservative half-median radius. All clustering runs on CPU with a
    local seed so the independently launched B1/B2 arms get identical starts.
    """
    if reference_mu.ndim != 2 or reference_mu.shape[1] != proxy.dim:
        raise ValueError(f"reference_mu must be [N,{proxy.dim}]")
    if reference_mu.shape[0] < proxy.num_proxies:
        raise ValueError("need at least one reference feature per proxy")
    reference = reference_mu.detach().to(device="cpu", dtype=torch.float32)
    if not bool(torch.isfinite(reference).all()):
        raise ValueError("reference_mu contains NaN or Inf")
    boundary = 1.0 / math.sqrt(proxy.c)
    if not bool((reference.norm(dim=-1) < boundary).all()):
        raise ValueError("reference_mu has points outside the Poincare ball")
    tangent = geoopt.PoincareBall(c=proxy.c).logmap0(reference)
    if not bool(torch.isfinite(tangent).all()):
        raise ValueError("log-mapped reference features are not finite")
    reference_norm = tangent.norm(dim=-1)
    median_norm = float(reference_norm.median())
    if median_norm <= 1e-8:
        raise ValueError("epoch-20 reference features have no usable radius")

    generator = torch.Generator(device="cpu").manual_seed(proxy.seed)
    subset_size = min(len(tangent), 2048)
    subset_indices = torch.randperm(len(tangent), generator=generator)[:subset_size]
    subset = tangent[subset_indices].contiguous()
    centers = subset[torch.randperm(subset_size, generator=generator)
                     [:proxy.num_proxies]].clone()
    empty_reseeds = 0
    iterations = 6
    for _ in range(iterations):
        distances = torch.cdist(subset, centers)
        assignment = distances.argmin(dim=1)
        counts = torch.bincount(assignment, minlength=proxy.num_proxies)
        sums = torch.zeros_like(centers)
        sums.index_add_(0, assignment, subset)
        updated = sums / counts.clamp_min(1).unsqueeze(1)
        empty = torch.nonzero(counts == 0, as_tuple=False).flatten()
        if len(empty):
            # Refill distinct empty clusters with the least represented data.
            farthest = torch.argsort(distances.min(dim=1).values,
                                     descending=True)[:len(empty)]
            updated[empty] = subset[farthest]
            empty_reseeds += len(empty)
        centers = updated
    center_norms = centers.norm(dim=-1)
    if not bool(torch.isfinite(centers).all()) or bool((center_norms <= 1e-8).any()):
        raise ValueError("feature-derived proxy directions are degenerate")

    init_cap = math.atanh(0.8) / math.sqrt(proxy.c)
    target = min(max(0.5 * median_norm, 0.05), init_cap)
    values = centers / center_norms.unsqueeze(1) * target
    value_sha256 = hashlib.sha256(values.numpy().tobytes()).hexdigest()
    proxy.tangent_proxies.copy_(values.to(device=proxy.tangent_proxies.device,
                                          dtype=proxy.tangent_proxies.dtype))
    final_distances = torch.cdist(subset, centers)
    final_counts = torch.bincount(final_distances.argmin(dim=1),
                                  minlength=proxy.num_proxies)
    return {
        "method": "epoch20_feature_tangent_kmeans_directions_half_median_radius",
        "label_free": True,
        "seed": proxy.seed,
        "reference_count": len(reference),
        "subset_count": subset_size,
        "iterations": iterations,
        "empty_cluster_reseeds": int(empty_reseeds),
        "occupied_clusters": int((final_counts > 0).sum()),
        "reference_median_tangent_norm": median_norm,
        "centroid_tangent_norm_min": float(center_norms.min()),
        "centroid_tangent_norm_median": float(center_norms.median()),
        "centroid_tangent_norm_max": float(center_norms.max()),
        "init_tangent_norm": target,
        "init_ball_norm": float(proxy.proxies().norm(dim=-1).median()),
        "initial_tangent_sha256": value_sha256,
    }


def git_checkout_state() -> dict:
    status = subprocess.run(["git", "status", "--porcelain"], cwd=REPO,
                            text=True, capture_output=True, check=False)
    return {"git_commit": git_commit(), "git_branch": git_branch(),
            "git_dirty": (bool(status.stdout.strip()) if status.returncode == 0 else None),
            "git_status_sha256": (hashlib.sha256(status.stdout.encode()).hexdigest()
                                  if status.returncode == 0 else None)}


def atomic_torch(path: Path, value: object) -> None:
    temporary = path.with_name(path.name + ".tmp")
    torch.save(value, temporary)
    os.replace(temporary, path)


def atomic_json(path: Path, value: object) -> None:
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8") as stream:
        json.dump(value, stream, indent=2, sort_keys=True, ensure_ascii=False,
                  allow_nan=False)
    os.replace(temporary, path)


def record_epoch(run_dir: Path, row: dict) -> None:
    """One atomic row per epoch; CSV is rebuilt so warmup rows remain present."""
    atomic_json(run_dir / f"metrics_epoch_{row['epoch']:03d}.json", row)
    rows = [json.loads(p.read_text(encoding="utf-8"))
            for p in sorted(run_dir.glob("metrics_epoch_*.json"))]
    fields = list(dict.fromkeys(key for item in rows for key in item))
    temporary = run_dir / "metrics.csv.tmp"
    with temporary.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)
    os.replace(temporary, run_dir / "metrics.csv")


def evaluate_with_classes(model: torch.nn.Module, loader: DataLoader,
                          device: torch.device, predictions_path: Path) -> dict:
    metrics = evaluate(model, loader, device, "test", predictions_path)
    with np.load(predictions_path) as saved:
        labels = saved["label"].reshape(-1)
        prediction = saved["logits"].argmax(axis=-1)
    counts = np.bincount(labels, minlength=40)
    correct = np.bincount(labels[labels == prediction], minlength=40)
    metrics["test_class_accuracy"] = [
        100.0 * float(correct[index]) / int(counts[index]) if counts[index] else None
        for index in range(40)]
    return metrics


def capture_rng() -> dict:
    return {"python": random.getstate(), "numpy": np.random.get_state(),
            "torch": torch.random.get_rng_state(),
            "cuda": torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None}


def restore_rng(state: dict) -> None:
    random.setstate(state["python"])
    np.random.set_state(state["numpy"])
    torch.random.set_rng_state(state["torch"])
    if state["cuda"] is not None and torch.cuda.is_available():
        torch.cuda.set_rng_state_all(state["cuda"])


def freeze_curvature(model: torch.nn.Module) -> None:
    model.manifold.requires_grad_(False)
    model.manifold2.requires_grad_(False)
    assert_manifold_contract(model)


def model_optimizer(model: torch.nn.Module, args: argparse.Namespace):
    optimizer = geoopt.optim.RiemannianSGD(
        [p for p in model.parameters() if p.requires_grad], lr=args.lr,
        momentum=0.9, weight_decay=args.weight_decay,
    )
    scheduler = CosineAnnealingLR(optimizer, args.epochs, eta_min=args.min_lr)
    assert_manifold_contract(model, optimizer)
    return optimizer, scheduler


class FlipSafeBatchSampler:
    """Keep selected samples, but place each of four classes in an 8-item block.

    Original HyCoRe constructs intra negatives by flipping batch dimension.
    A fully shuffled balanced batch would put approximately one quarter of
    negatives in the same class. Grouping the four sampled classes in their
    first-seen random order ensures each mirrored pair crosses classes.
    Within each class the base sampler's random sample order is preserved.
    """

    def __init__(self, base: ClassBalancedBatchSampler, labels: np.ndarray):
        self.base = base
        self.labels = labels

    def __len__(self) -> int:
        return len(self.base)

    def __iter__(self):
        for batch in self.base:
            groups: dict[int, list[int]] = {}
            for index in batch:
                groups.setdefault(int(self.labels[index]), []).append(index)
            if len(groups) != 4 or any(len(indices) != 8 for indices in groups.values()):
                raise RuntimeError("balanced batch must contain exactly four 8-sample classes")
            ordered = [index for indices in groups.values() for index in indices]
            ordered_labels = [int(self.labels[index]) for index in ordered]
            if any(left == right for left, right in
                   zip(ordered_labels, reversed(ordered_labels))):
                raise RuntimeError("flip-negative class collision")
            yield ordered


def flip_safe_fixed_probe_data(model: torch.nn.Module, proxy: ProxyHierarchy,
                               points: np.ndarray, labels: np.ndarray,
                               args: argparse.Namespace, device: torch.device):
    """Reindex v2's fixed probe into the same flip-safe layout as training."""
    first, second, initial_mu, mined, edges = fixed_probe_data(
        model, proxy, points, labels, args, device)
    groups: dict[int, list[int]] = {}
    for position, label in enumerate(first[1].reshape(-1).tolist()):
        groups.setdefault(int(label), []).append(position)
    if len(groups) != 4 or any(len(group) != 8 for group in groups.values()):
        raise RuntimeError("fixed probe must have four 8-sample classes")
    permutation = torch.tensor([position for group in groups.values()
                                for position in group], dtype=torch.long)
    inverse = torch.empty_like(permutation)
    inverse[permutation] = torch.arange(len(permutation))
    first = tuple(value[permutation] for value in first)
    second = tuple(value[permutation] for value in second)
    initial_mu = initial_mu[permutation]
    mined = {key: inverse.to(value.device)[value] if key in ("in", "out") else value
             for key, value in mined.items()}
    edges = {(int(inverse[i]), int(inverse[j])) for i, j in edges}
    gold = first[1].reshape(-1)
    if bool((gold == torch.flip(gold, (0,))).any()):
        raise RuntimeError("fixed probe flip-negative class collision")
    return first, second, initial_mu, mined, edges


def loader_for_epoch(dataset: PointClouds, labels: np.ndarray,
                     args: argparse.Namespace, epoch: int) -> DataLoader:
    sampler = ClassBalancedBatchSampler(
        labels, args.classes_per_batch, args.samples_per_class, args.seed,
        batches_per_epoch=args.steps_per_epoch,
    )
    sampler.set_epoch(epoch)
    # A fresh worker generator makes augmentation and sample order identical
    # in B1/B2 even though the two losses consume different CUDA random draws.
    worker_generator = torch.Generator().manual_seed(args.seed + 101 + epoch * 1009)
    return DataLoader(dataset, batch_sampler=FlipSafeBatchSampler(sampler, labels),
                      num_workers=args.workers,
                      pin_memory=True, generator=worker_generator,
                      persistent_workers=False)


def hierarchy_scale(args: argparse.Namespace, epoch: int) -> float:
    return args.target_hier_scale * min(
        1.0, (epoch - args.warmup_epochs + 1) / args.ramp_epochs,
    )


def forward_losses(model: torch.nn.Module, proxy: ProxyHierarchy | None,
                   points: torch.Tensor, labels: torch.Tensor,
                   args: argparse.Namespace, epoch: int, batch_index: int,
                   device: torch.device) -> dict:
    data = points.to(device, non_blocking=True).transpose(1, 2).contiguous()
    labels = labels.reshape(-1).to(device, non_blocking=True)
    # Exact original HyCoRe sampling. Both calls mutate views of the same
    # data tensor; ``data`` (the parent) has therefore also been modified.
    _, data, n_points = get_children_np(data, kmin=800, kmax=1024)
    margin, pos_data, _ = get_children_np(
        data, starting=n_points, kmin=200, kmax=600,
    )
    pos_mu, _ = model(pos_data, emb=True)
    mu, logits = model(data)
    parent_norm, child_norm, positive_distance, negative_distance, triplet, radial = hype_triplet_losses(
        mu, pos_mu, hier_margin=margin, contr_margin=4, ball_dim=256,
    )
    ce = cal_loss(logits, labels)
    zero = mu.sum() * 0.0
    result = {"ce": ce, "intra": triplet + radial,
              "intra_triplet": triplet, "intra_radial": radial,
              "parent_norm": parent_norm, "child_norm": child_norm,
              "positive_distance": positive_distance,
              "negative_distance": negative_distance,
              "mu": mu, "logits": logits, "in": zero, "out": zero,
              "proxy": zero, "mining_stats": {}, "in_stats": {},
              "out_stats": {}, "proxy_stats": {}}
    if proxy is None:
        return result
    radius = mu.detach().norm(dim=-1)
    if not bool(torch.isfinite(radius).all()) or float(radius.max()) > 1.01:
        raise FloatingPointError(f"invalid raw embedding radius {float(radius.max())}")
    hier_mu = proxy.ball.projx(mu.float())
    projected = int(((hier_mu.detach() - mu.detach()).norm(dim=-1) > 1e-6).sum())
    with fixed_rng(args.seed + epoch * 1000003 + batch_index, device):
        mined = mine_batch_triplets(hier_mu.detach(), labels, k_in=args.k_in,
                                    seed=args.seed + epoch * 1000003 + batch_index,
                                    hard_ratio=0.5)
        in_loss, in_stats = proxy.sample_loss(
            hier_mu, triplet_columns(mined["in"]), tau=args.tau, margin=args.margin)
        out_loss, out_stats = proxy.sample_loss(
            hier_mu, triplet_columns(mined["out"]), tau=args.tau, margin=args.margin)
        proxy_loss, proxy_stats = proxy.proxy_loss(
            k=args.proxy_k, t_per_anchor=args.proxy_triples_per_anchor,
            tau=args.tau, margin=args.margin)
    mined["stats"].update({
        "raw_radius_max": float(radius.max()),
        "projected_radius_max": float(hier_mu.detach().norm(dim=-1).max()),
        "raw_outside_samples": int((radius >= 1).sum()),
        "projected_samples": projected,
    })
    result.update({"in": in_loss, "out": out_loss, "proxy": proxy_loss,
                   "hier_mu": hier_mu, "mining_stats": mined["stats"],
                   "in_stats": in_stats, "out_stats": out_stats,
                   "proxy_stats": proxy_stats})
    return result


def measure_parameters(model: torch.nn.Module) -> dict[str, torch.nn.Parameter]:
    return {name: next((p for param_name, p in model.named_parameters()
                        if param_name.startswith(name + ".") and p.requires_grad), None)
            for name in BACKBONE_PREFIXES}


def train_epoch(model: torch.nn.Module, proxy: ProxyHierarchy | None,
                train_data: PointClouds, labels_all: np.ndarray,
                optimizer: torch.optim.Optimizer,
                proxy_optimizer: torch.optim.Optimizer | None,
                betas: dict[str, float], args: argparse.Namespace,
                epoch: int, device: torch.device) -> dict:
    model.train()
    if proxy is not None:
        proxy.train()
    seed_all(args.seed + epoch * 1009)
    loader = loader_for_epoch(train_data, labels_all, args, epoch)
    start = time.monotonic()
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)
    keys = ("loss", "ce", "intra", "intra_triplet", "intra_radial",
            "parent_norm", "child_norm", "positive_distance", "negative_distance", "in", "out",
            "proxy", "base", "weighted_in", "weighted_out", "weighted_proxy",
            "in_triplets", "out_triplets", "proxy_triplets", "in_active",
            "out_active", "proxy_active", "in_valid", "out_valid", "proxy_valid",
            "in_collisions", "out_collisions", "proxy_collisions", "eligible_in",
            "eligible_out", "proxy_eligible", "projected_samples",
            "raw_outside_samples", "grad_norm", "flip_negative_same_class")
    sums = {key: 0.0 for key in keys}
    confusion = torch.zeros(40, 40, dtype=torch.long)
    exposure = torch.zeros(40, dtype=torch.long)
    seen_ids: set[int] = set()
    max_raw, max_projected = 0.0, 0.0
    params = measure_parameters(model)
    step_diagnostics: dict[str, float] = {}
    batches = 0
    scale = hierarchy_scale(args, epoch) if proxy is not None else 0.0
    for batch_index, (points, labels, ids) in enumerate(loader):
        if args.max_batches and batch_index >= args.max_batches:
            break
        optimizer.zero_grad(set_to_none=True)
        if proxy_optimizer is not None:
            proxy_optimizer.zero_grad(set_to_none=True)
        try:
            values = forward_losses(model, proxy, points, labels, args,
                                    epoch, batch_index, device)
        except Exception as error:
            raise RuntimeError(f"epoch {epoch+1} batch {batch_index}: {error}") from error
        base = values["ce"] + ALPHA_INTRA * values["intra"]
        weighted_in = scale * betas["in"] * values["in"]
        weighted_out = scale * (betas["out"] if args.arm == "B2" else 0.0) * values["out"]
        weighted_proxy = scale * betas["p"] * values["proxy"]
        loss = base + weighted_in + weighted_out + weighted_proxy
        if not bool(torch.isfinite(loss)):
            raise FloatingPointError(f"non-finite loss epoch={epoch+1} batch={batch_index}")
        loss.backward()
        all_params = [p for group in optimizer.param_groups for p in group["params"]]
        if proxy_optimizer is not None:
            all_params += [p for group in proxy_optimizer.param_groups for p in group["params"]]
        norm = torch.nn.utils.clip_grad_norm_(all_params, 1.0)
        if not bool(torch.isfinite(norm)):
            raise FloatingPointError(f"non-finite gradient epoch={epoch+1} batch={batch_index}")
        if batch_index == 0:
            before = {name: p.detach().clone() for name, p in params.items() if p is not None}
            step_diagnostics = {
                "grad_" + name: float(p.grad.norm()) if p is not None and p.grad is not None else 0.0
                for name, p in params.items()}
            if proxy is not None:
                step_diagnostics["grad_proxy"] = (
                    float(proxy.tangent_proxies.grad.norm())
                    if proxy.tangent_proxies.grad is not None else 0.0)
        optimizer.step()
        if proxy_optimizer is not None:
            proxy_optimizer.step()
        if batch_index == 0:
            step_diagnostics.update({"update_" + name: float((p.detach() - before[name]).norm())
                                     for name, p in params.items() if p is not None})
        for key in ("ce", "intra", "intra_triplet", "intra_radial",
                    "parent_norm", "child_norm", "positive_distance", "negative_distance",
                    "in", "out", "proxy"):
            sums[key] += float(values[key].detach())
        for key, tensor in (("base", base), ("weighted_in", weighted_in),
                            ("weighted_out", weighted_out), ("weighted_proxy", weighted_proxy),
                            ("loss", loss)):
            sums[key] += float(tensor.detach())
        sums["grad_norm"] += float(norm)
        labels_cpu = labels.reshape(-1).cpu()
        if bool((labels_cpu == torch.flip(labels_cpu, (0,))).any()):
            raise RuntimeError("HyCoRe flipped negative has same class as anchor")
        prediction = values["logits"].detach().argmax(-1).cpu()
        for gold, pred in zip(labels_cpu.tolist(), prediction.tolist()):
            confusion[gold, pred] += 1
        exposure += torch.bincount(labels_cpu, minlength=40)
        sums["flip_negative_same_class"] += float(
            (labels_cpu == torch.flip(labels_cpu, (0,))).float().mean())
        seen_ids.update(ids.reshape(-1).tolist())
        if proxy is not None:
            mine = values["mining_stats"]
            sums["eligible_in"] += mine.get("eligible_in_anchors", 0)
            sums["eligible_out"] += mine.get("eligible_out_anchors", 0)
            sums["projected_samples"] += mine.get("projected_samples", 0)
            sums["raw_outside_samples"] += mine.get("raw_outside_samples", 0)
            max_raw = max(max_raw, mine.get("raw_radius_max", 0.0))
            max_projected = max(max_projected, mine.get("projected_radius_max", 0.0))
            for branch in ("in", "out", "proxy"):
                stats = values[branch + "_stats"]
                for suffix, field in (("triplets", "triplets"), ("active", "active_triplets"),
                                      ("valid", "valid_triplets"), ("collisions", "collisions")):
                    sums[branch + "_" + suffix] += stats.get(field, 0)
            sums["proxy_eligible"] += values["proxy_stats"].get("eligible_anchors", 0)
        batches += 1
    if batches == 0:
        raise RuntimeError("no training batches")
    result = {"train_" + key: value / batches for key, value in sums.items()}
    result.update({"train_oa": 100 * float(confusion.diagonal().sum()) / int(confusion.sum()),
                   "train_aa": 100 * float((confusion.diagonal().float() /
                                            confusion.sum(-1).clamp_min(1)).mean()),
                   "train_class_accuracy": [100 * float(confusion[i, i]) /
                                            max(int(confusion[i].sum()), 1) for i in range(40)],
                   "train_class_exposure": exposure.tolist(),
                   "train_unique_samples": len(seen_ids),
                   "train_unique_coverage": len(seen_ids) / len(labels_all),
                   "train_max_raw_radius": max_raw,
                   "train_max_projected_radius": max_projected,
                   "train_batches": batches,
                   "train_seconds": time.monotonic() - start,
                   "peak_memory_mb": (torch.cuda.max_memory_allocated(device) / 1024**2
                                      if device.type == "cuda" else 0.0)})
    for branch in ("in", "out", "proxy"):
        result["train_" + branch + "_active_rate"] = (
            sums[branch + "_active"] / sums[branch + "_triplets"]
            if sums[branch + "_triplets"] else None)
    if proxy is None:
        # During original HyCoRe warmup, HIER does not exist. Null means
        # not applicable, whereas zero could falsely suggest a satisfied loss.
        hier_keys = ("in", "out", "proxy", "weighted_in", "weighted_out",
                     "weighted_proxy", "eligible_in", "eligible_out",
                     "proxy_eligible", "projected_samples", "raw_outside_samples",
                     "max_raw_radius", "max_projected_radius")
        for key in hier_keys:
            result["train_" + key] = None
        for branch in ("in", "out", "proxy"):
            for suffix in ("triplets", "active", "valid", "collisions", "active_rate"):
                result["train_" + branch + "_" + suffix] = None
    result.update(step_diagnostics)
    assert_manifold_contract(model, optimizer)
    return result


def calibrate_shared(model: torch.nn.Module, proxy: ProxyHierarchy,
                     train_data: PointClouds, labels_all: np.ndarray,
                     args: argparse.Namespace, device: torch.device) -> dict:
    model.train()
    proxy.train()
    saved_buffers = {name: value.detach().clone()
                     for name, value in model.named_buffers()}
    # Fixed sampler + worker seeds and restored RNG avoid consuming the saved
    # warmup continuation state. Both branches load identical coefficients.
    reports = []
    with fixed_rng(args.seed + 5005, device):
        loader = loader_for_epoch(train_data, labels_all, args, args.warmup_epochs)
        for batch_index, (points, labels, ids) in enumerate(loader):
            if batch_index >= args.calibration_batches:
                break
            values = forward_losses(model, proxy, points, labels, args,
                                    args.warmup_epochs, batch_index, device)
            reports.append(calibrate(values, proxy))
            del values
    betas = {}
    for key in ("in", "out", "p"):
        finite = [r["suggested_betas"][key] for r in reports
                  if r["suggested_betas"][key] is not None and
                  math.isfinite(r["suggested_betas"][key])]
        if not finite or float(np.median(finite)) <= 0:
            raise RuntimeError(f"calibration has no usable {key} gradient; refusing empty HIER branch")
        betas[key] = min(float(np.median(finite)), MAX_BETA)
    coverage = {key: sum(int(r[key]["valid_triplets"]) for r in reports)
                for key in ("in", "out", "proxy")}
    if any(count == 0 for count in coverage.values()):
        raise RuntimeError(f"calibration HIER triplet coverage is empty: {coverage}")
    # Short non-mutating pilot at first ramp scale. Cap the proxy LR so its
    # largest predicted tangent update is <=5% of the initial tangent radius.
    with fixed_rng(args.seed + 5006, device):
        first = next(iter(loader_for_epoch(train_data, labels_all, args,
                                           args.warmup_epochs)))
        values = forward_losses(model, proxy, first[0], first[1], args,
                                args.warmup_epochs, 0, device)
        pilot_coverage = {key: int(values[key + "_stats"]["valid_triplets"])
                          for key in ("in", "out", "proxy")}
        if any(count == 0 for count in pilot_coverage.values()):
            raise RuntimeError(f"pilot HIER triplet coverage is empty: {pilot_coverage}")
        first_scale = args.target_hier_scale / args.ramp_epochs
        pilot = first_scale * (betas["in"] * values["in"] +
                               betas["out"] * values["out"] +
                               betas["p"] * values["proxy"])
        grad = norm_of_gradient(pilot, proxy.tangent_proxies)
        max_row_grad = float(grad.norm(dim=-1).max())
    with torch.no_grad():
        for name, value in model.named_buffers():
            value.copy_(saved_buffers[name])
    initial_radius = float(proxy.tangent_proxies.detach().norm(dim=-1).median())
    safe_lr = 0.05 * initial_radius / max(max_row_grad, 1e-12)
    proxy_lr = min(args.proxy_lr_ceiling, safe_lr)
    if not math.isfinite(proxy_lr) or proxy_lr <= 0:
        raise RuntimeError("proxy LR pilot produced invalid value")
    return {"betas": betas, "proxy_lr": proxy_lr,
            "proxy_min_lr": proxy_lr * 0.1,
            "beta_cap": MAX_BETA, "target_hier_scale": args.target_hier_scale,
            "pilot_max_proxy_row_grad": max_row_grad,
            "pilot_initial_tangent_radius": initial_radius,
            "pilot_safe_lr": safe_lr,
            "calibration_valid_triplets": coverage,
            "pilot_valid_triplets": pilot_coverage,
            "rule": "v2 gradient balance; cap beta at 10; first-ramp proxy step <=5% initial tangent radius",
            "per_batch": reports}


def diagnostics_epoch(model: torch.nn.Module, proxy: ProxyHierarchy,
                      fixed: dict, initial_tangent: torch.Tensor,
                      occupancy_reference: torch.Tensor, betas: dict,
                      args: argparse.Namespace, epoch: int,
                      device: torch.device) -> tuple[dict, dict]:
    first, second = fixed["first"], fixed["second"]
    initial_mu = fixed["initial_mu"].to(device)
    fixed_triplets = fixed["triplets"]
    initial_edges = set(map(tuple, fixed["initial_edges"]))
    previous_edges = set(map(tuple, fixed["previous_edges"]))
    model.eval()
    proxy.eval()
    with fixed_rng(args.seed + 9001, device), torch.no_grad():
        current_mu, _ = model(first[0].to(device).transpose(1, 2))
        current_mu = proxy.ball.projx(current_mu)
    with fixed_rng(args.seed + 9001, device), torch.no_grad():
        second_mu, _ = model(second[0].to(device).transpose(1, 2))
        second_mu = proxy.ball.projx(second_mu)
    edges = probe_neighbour_edges(current_mu, first[1], proxy, args.k_in)
    other_edges = probe_neighbour_edges(second_mu, second[1], proxy, args.k_in)
    result = {"probe_knn_jaccard_initial": edge_jaccard(initial_edges, edges),
              "probe_knn_jaccard_previous": edge_jaccard(previous_edges, edges),
              "probe_knn_jaccard_views": edge_jaccard(edges, other_edges)}
    result.update(probe_distance_stats(current_mu, first[1], proxy))
    with fixed_rng(args.seed + 9002, device):
        values = forward_losses(model, proxy, first[0], first[1], args,
                                epoch, 0, device)
        in_loss, in_stats = proxy.sample_loss(
            values["hier_mu"], triplet_columns(fixed_triplets["in"]),
            tau=args.tau, margin=args.margin)
        out_loss, out_stats = proxy.sample_loss(
            values["hier_mu"], triplet_columns(fixed_triplets["out"]),
            tau=args.tau, margin=args.margin)
        base = values["ce"] + ALPHA_INTRA * values["intra"]
        mu, tangent = values["mu"], proxy.tangent_proxies
        gradients = {"base_mu": norm_of_gradient(base, mu),
                     "in_mu": norm_of_gradient(in_loss, mu),
                     "out_mu": norm_of_gradient(out_loss, mu),
                     "in_proxy": norm_of_gradient(in_loss, tangent),
                     "out_proxy": norm_of_gradient(out_loss, tangent),
                     "proxy_only_proxy": norm_of_gradient(values["proxy"], tangent)}
        scale = hierarchy_scale(args, epoch) if epoch >= args.warmup_epochs else 0.0
        b_out = betas["out"] if args.arm == "B2" else 0.0
        result.update({
            "probe_in_loss": float(in_loss.detach()),
            "probe_out_loss": float(out_loss.detach()),
            "probe_proxy_loss": float(values["proxy"].detach()),
            "probe_base_mu_grad": float(gradients["base_mu"].norm()),
            "probe_weighted_in_mu_grad": float((scale * betas["in"] * gradients["in_mu"]).norm()),
            "probe_weighted_out_mu_grad": float((scale * b_out * gradients["out_mu"]).norm()),
            "probe_weighted_in_proxy_grad": float((scale * betas["in"] * gradients["in_proxy"]).norm()),
            "probe_weighted_out_proxy_grad": float((scale * b_out * gradients["out_proxy"]).norm()),
            "probe_weighted_proxy_only_grad": float((scale * betas["p"] * gradients["proxy_only_proxy"]).norm()),
            "probe_weighted_total_proxy_grad": float((scale * (
                betas["in"] * gradients["in_proxy"] + b_out * gradients["out_proxy"] +
                betas["p"] * gradients["proxy_only_proxy"])).norm()),
        })
        for name, stats in (("in", in_stats), ("out", out_stats)):
            valid = stats["valid_triplets"]
            result["probe_" + name + "_valid"] = valid
            result["probe_" + name + "_margin_satisfied_rate"] = (
                1 - stats["active_triplets"] / valid if valid else None)
    result.update(fixed_triplet_metrics(
        proxy, initial_tangent, initial_mu, current_mu.detach(),
        triplet_columns(fixed_triplets["in"]),
        seed=args.seed + 9003, tau=args.tau, margin=args.margin))
    geometry, snapshot = proxy_geometry(proxy, initial_tangent, occupancy_reference)
    result.update({key: float(value) for key, value in geometry.items()})
    fixed["previous_edges"] = sorted(edges)
    return result, snapshot


def checkpoint(model: torch.nn.Module, optimizer: torch.optim.Optimizer,
               scheduler: CosineAnnealingLR, epoch_number: int,
               args: argparse.Namespace, row: dict,
               proxy: ProxyHierarchy | None = None,
               proxy_optimizer: torch.optim.Optimizer | None = None,
               proxy_scheduler: CosineAnnealingLR | None = None,
               fixed: dict | None = None) -> dict:
    return {"net": model.state_dict(), "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(), "epoch": epoch_number,
            "rng": capture_rng(), "sampler_next_epoch": epoch_number,
            "worker_seed_rule": "seed+101+epoch*1009", "args": serializable_args(args),
            "metrics": row, "proxy": proxy.state_dict() if proxy else None,
            "proxy_optimizer": proxy_optimizer.state_dict() if proxy_optimizer else None,
            "proxy_scheduler": proxy_scheduler.state_dict() if proxy_scheduler else None,
            "fixed_probe": fixed}


def main() -> None:
    args = arguments()
    if args.device.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    device = torch.device(args.device)
    seed_all(args.seed)
    run_dir = args.run_dir.resolve()
    if run_dir.exists() and not (run_dir / "last.pth").is_file():
        # A launcher may precreate its log in this directory, but an old
        # manifest/metrics without a checkpoint must not be overwritten.
        if any((run_dir / name).exists() for name in
               ("manifest.json", "metrics.csv", "calibration.json")):
            raise FileExistsError(f"old run dir without resumable last.pth: {run_dir}")
    run_dir.mkdir(parents=True, exist_ok=True)
    train_points, train_labels, train_shards = load_shards(args.data_dir, "train")
    class_counts = np.bincount(train_labels, minlength=40)
    if (len(np.unique(train_labels)) != 40 or class_counts.min() < 8 or
            len(train_labels) // args.batch_size != args.steps_per_epoch):
        raise ValueError("expected 40 ModelNet40 classes, >=8 samples/class, and 307 full 32-item steps")
    args.data_dir = args.data_dir.resolve(strict=True)
    args.run_dir = args.run_dir.resolve()
    if args.warmup_checkpoint is not None:
        args.warmup_checkpoint = args.warmup_checkpoint.resolve(strict=True)
    args.train_labels_sha256 = hashlib.sha256(train_labels.tobytes()).hexdigest()
    args.train_shards_sorted = train_shards
    train_data = PointClouds(train_points, train_labels, 1024, "train", args.seed)
    test_loader = None
    test_shards = None
    if not args.skip_test:
        test_points, test_labels, test_shards = load_shards(args.data_dir, "test")
        test_loader = DataLoader(PointClouds(test_points, test_labels, 1024, "eval", args.seed),
                                 batch_size=32, shuffle=False, num_workers=args.workers,
                                 pin_memory=True)
    manifest_path = run_dir / "manifest.json"
    manifest = {"status": "running", "phase": args.phase, "arm": args.arm,
                "started_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
                "command": sys.argv, "args": serializable_args(args),
                "train_shards_sorted": train_shards,
                "train_labels_sha256": hashlib.sha256(train_labels.tobytes()).hexdigest(),
                "train_count": len(train_labels), "test_shards_sorted": test_shards,
                "torch": torch.__version__, "geoopt": getattr(geoopt, "__version__", "unknown"),
                "gpu_name": torch.cuda.get_device_name(device) if device.type == "cuda" else None,
                "cuda_visible_devices": os.environ.get("CUDA_VISIBLE_DEVICES"),
                "protocol": "HyCoRe original CE/intra/part sampling + paired online HIER",
                **git_checkout_state()}
    atomic_json(manifest_path, manifest)
    try:
        model = Hype_pointMLP().to(device)
        freeze_curvature(model)
        optimizer, scheduler = model_optimizer(model, args)
        proxy = proxy_optimizer = proxy_scheduler = fixed = None
        betas = {"in": 0.0, "out": 0.0, "p": 0.0}
        start_epoch = 0
        own_last = run_dir / "last.pth"
        if own_last.is_file():
            state = torch.load(own_last, map_location="cpu", weights_only=False)
            previous_args = state["args"]
            current_args = serializable_args(args)
            mismatched = [key for key, value in current_args.items()
                          if key != "device" and previous_args.get(key) != value]
            if mismatched:
                raise ValueError("existing run configuration/data mismatch: " +
                                 ", ".join(mismatched))
            model.load_state_dict(state["net"])
            optimizer.load_state_dict(state["optimizer"])
            scheduler.load_state_dict(state["scheduler"])
            start_epoch = state["epoch"]
            restore_rng(state["rng"])
        elif args.phase == "branch":
            source = args.warmup_checkpoint.resolve(strict=True)
            state = torch.load(source, map_location="cpu", weights_only=False)
            if state["epoch"] != args.warmup_epochs or state["args"]["phase"] != "warmup":
                raise ValueError("branch source is not the completed shared warmup")
            shared_keys = ("seed", "epochs", "warmup_epochs", "batch_size",
                           "num_points", "steps_per_epoch", "lr", "min_lr",
                           "weight_decay", "train_labels_sha256", "train_shards_sorted")
            mismatched = [key for key in shared_keys
                          if state["args"].get(key) != serializable_args(args)[key]]
            if mismatched:
                raise ValueError("warmup training configuration/data mismatch: " +
                                 ", ".join(mismatched))
            model.load_state_dict(state["net"])
            optimizer.load_state_dict(state["optimizer"])
            scheduler.load_state_dict(state["scheduler"])
            start_epoch = state["epoch"]
            restore_rng(state["rng"])
            manifest["warmup_checkpoint"] = str(source)
            manifest["warmup_checkpoint_sha256"] = sha256(source)
            for previous in sorted(source.parent.glob("metrics_epoch_*.json")):
                target = run_dir / previous.name
                atomic_json(target, json.loads(previous.read_text(encoding="utf-8")))
            initial_mu_path = source.parent / "initial_mu.pt"
            initial_features = torch.load(initial_mu_path, map_location="cpu", weights_only=False)
            if initial_features.shape != (len(train_labels), 256):
                raise ValueError("warmup feature cache shape mismatch")
            proxy = ProxyHierarchy(num_proxies=args.proxy_count, dim=256, c=1,
                                   seed=args.seed).to(device)
            initialization = initialize_proxies_from_features(proxy, initial_features)
            atomic_json(run_dir / "proxy_initialization.json", initialization)
            calibration = calibrate_shared(model, proxy, train_data, train_labels, args, device)
            betas = calibration["betas"]
            atomic_json(run_dir / "calibration.json", calibration)
            proxy_optimizer = geoopt.optim.RiemannianSGD(
                proxy.parameters(), lr=calibration["proxy_lr"], momentum=0.9,
                weight_decay=args.weight_decay)
            proxy_scheduler = CosineAnnealingLR(
                proxy_optimizer, args.epochs - args.warmup_epochs,
                eta_min=calibration["proxy_min_lr"])
            # Probe starts from the common branch point. B1/B2 are identical.
            first, second, initial_mu, triplets, edges = flip_safe_fixed_probe_data(
                model, proxy, train_points, train_labels, args, device)
            fixed = {"first": first, "second": second,
                     "initial_mu": initial_mu,
                     "triplets": triplets,
                     "initial_edges": sorted(edges),
                     "previous_edges": sorted(edges)}
            atomic_torch(run_dir / "fixed_probe.pt", fixed)
            occupancy_ids = np.concatenate([
                np.flatnonzero(train_labels == label)[:10] for label in np.unique(train_labels)])
            atomic_torch(run_dir / "occupancy_reference.pt", initial_features[occupancy_ids])
            atomic_torch(run_dir / "initial_tangent.pt", proxy.tangent_proxies.detach().cpu())
            manifest["occupancy_reference_ids"] = occupancy_ids.tolist()
            # Baseline predictions and proxy snapshot before first HIER update.
            if test_loader is not None:
                with fixed_rng(args.seed + 9020, device):
                    baseline_test = evaluate_with_classes(
                        model, test_loader, device,
                        run_dir / f"predictions_epoch_{start_epoch:03d}.npz")
            else:
                baseline_test = {}
            baseline_probe, snapshot = diagnostics_epoch(
                model, proxy, fixed, proxy.tangent_proxies.detach().clone(),
                initial_features[occupancy_ids].to(device), betas, args,
                start_epoch - 1, device)
            atomic_json(run_dir / "branch_baseline.json",
                        {"epoch": start_epoch, **baseline_test, **baseline_probe})
            atomic_torch(run_dir / f"proxy_diagnostic_epoch_{start_epoch:03d}.pt", snapshot)
            # Calibration and probes are read-only; restore shared RNG.
            restore_rng(state["rng"])
        if args.phase == "branch" and own_last.is_file():
            calibration = json.loads((run_dir / "calibration.json").read_text(encoding="utf-8"))
            betas = calibration["betas"]
            proxy = ProxyHierarchy(num_proxies=args.proxy_count, dim=256, c=1,
                                   seed=args.seed).to(device)
            proxy.load_state_dict(state["proxy"])
            proxy_optimizer = geoopt.optim.RiemannianSGD(
                proxy.parameters(), lr=calibration["proxy_lr"], momentum=0.9,
                weight_decay=args.weight_decay)
            proxy_optimizer.load_state_dict(state["proxy_optimizer"])
            proxy_scheduler = CosineAnnealingLR(
                proxy_optimizer, args.epochs - args.warmup_epochs,
                eta_min=calibration["proxy_min_lr"])
            proxy_scheduler.load_state_dict(state["proxy_scheduler"])
            fixed = state["fixed_probe"]
        if args.phase == "warmup" and start_epoch >= args.warmup_epochs:
            if not (run_dir / "initial_mu.pt").is_file():
                features = initialization_features(model, train_points, train_labels,
                                                   args, device)
                atomic_torch(run_dir / "initial_mu.pt", features)
            manifest["initial_mu_sha256"] = sha256(run_dir / "initial_mu.pt")
            manifest["status"] = "completed"
            print("warmup already completed", flush=True)
            return
        stop_epoch = args.warmup_epochs if args.phase == "warmup" else args.epochs
        for epoch in range(start_epoch, stop_epoch):
            epoch_start = time.monotonic()
            lr = optimizer.param_groups[0]["lr"]
            proxy_lr = proxy_optimizer.param_groups[0]["lr"] if proxy_optimizer else None
            train_metrics = train_epoch(model, proxy, train_data, train_labels,
                                        optimizer, proxy_optimizer, betas,
                                        args, epoch, device)
            diagnostic_start = time.monotonic()
            if proxy is not None:
                initial_tangent = torch.load(run_dir / "initial_tangent.pt",
                                             map_location=device, weights_only=False)
                occupancy_reference = torch.load(run_dir / "occupancy_reference.pt",
                                                 map_location=device, weights_only=False)
                probe_metrics, snapshot = diagnostics_epoch(
                    model, proxy, fixed, initial_tangent, occupancy_reference,
                    betas, args, epoch, device)
                snapshot["tangent"] = proxy.tangent_proxies.detach().cpu()
                atomic_torch(run_dir / f"proxy_diagnostic_epoch_{epoch+1:03d}.pt", snapshot)
            else:
                probe_metrics = {}
            if test_loader is not None:
                with fixed_rng(args.seed + 9020, device):
                    test_metrics = evaluate_with_classes(
                        model, test_loader, device,
                        run_dir / f"predictions_epoch_{epoch+1:03d}.npz")
            else:
                test_metrics = {"test_loss": None, "test_oa": None, "test_aa": None}
            scheduler.step()
            if proxy_scheduler is not None:
                proxy_scheduler.step()
            row = {"epoch": epoch + 1, "phase": args.phase, "arm": args.arm,
                   "lr": lr, "proxy_lr": proxy_lr,
                   "hier_scale": hierarchy_scale(args, epoch) if proxy is not None else None,
                   "beta_in": betas["in"] if proxy is not None else None,
                   "beta_out_effective": (betas["out"] if args.arm == "B2" else 0.0)
                                         if proxy is not None else None,
                   "beta_p": betas["p"] if proxy is not None else None,
                   **train_metrics, **probe_metrics, **test_metrics,
                   "diagnostic_seconds": time.monotonic() - diagnostic_start,
                   "epoch_wall_seconds": time.monotonic() - epoch_start}
            record_epoch(run_dir, row)
            state = checkpoint(model, optimizer, scheduler, epoch + 1, args,
                               row, proxy, proxy_optimizer, proxy_scheduler, fixed)
            atomic_torch(own_last, state)
            if (epoch + 1) % args.save_every == 0:
                atomic_torch(run_dir / f"checkpoint_epoch_{epoch+1:03d}.pth", state)
            print("epoch:", json.dumps(row, ensure_ascii=False), flush=True)
        if args.phase == "warmup":
            # One deterministic pass over current features; no old teacher.
            features = initialization_features(model, train_points, train_labels,
                                               args, device)
            atomic_torch(run_dir / "initial_mu.pt", features)
            manifest["initial_mu_sha256"] = sha256(run_dir / "initial_mu.pt")
        manifest["status"] = "completed"
    except Exception as error:
        manifest["status"] = "failed"
        manifest["error"] = repr(error)
        raise
    finally:
        manifest["finished_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()
        atomic_json(manifest_path, manifest)


if __name__ == "__main__":
    main()
